language: node_js
sudo: false
node_js:
- '8.6.0'

cache:
  directories:
     - ./node_modules

install:
  - npm i

before_script:

script:
  - npm run coverage

after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- rm -rf ./coverage
